# config.yaml

# 모델 파라미터
model_params:
   N_MAX: 200
   embedding_dim: 256
   encoder_layer_num: 2
   qkv_dim: 16
   head_num: 16
   ff_hidden_dim: 512
   ffd: 'siglu'
   norm_type: 'rms'
   logit_clipping: 10


# 옵티마이저 및 스케줄러 파라미터
optimizer_params:
    optimizer:
        lr: 2e-4
        weight_decay: 1e-6
    max_grad_norm: 1.0        
    scheduler:
        name: 'MultiStepLR'
        milestones: [80, 95]
        gamma: 0.1

# 트레이너 파라미터
trainer_params:
    epochs: 100
    train_step: 100  # 1 에폭당 훈련 스텝 수
    model_save_interval: 5
    model_load:
        enable: False
        path: 'transformer_solver/result/...'
        epoch: 100